from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
import os
import matplotlib.pyplot as plt

def generate_report(data: dict) -> str:
    ip = data.get("ip", "N/A")
    domain = data.get("domain", "N/A")
    email = data.get("email", "N/A")

    # Risk hesapla
    ip_risk = len(ip) * 5 % 100
    domain_risk = len(domain) * 7 % 100
    email_risk = len(email) * 9 % 100

    # Grafik oluştur
    fig, ax = plt.subplots()
    risks = [ip_risk, domain_risk, email_risk]
    labels = ["IP", "Domain", "Email"]
    ax.bar(labels, risks, color=["#007ACC", "#FF8800", "#33CC33"])
    ax.set_ylabel("Risk Score (%)")
    ax.set_ylim(0, 100)
    graph_path = "reports/risk_chart.png"
    os.makedirs("reports", exist_ok=True)
    plt.savefig(graph_path)
    plt.close()

    # PDF oluştur
    pdf_path = "reports/threat_report.pdf"
    c = canvas.Canvas(pdf_path, pagesize=A4)
    width, height = A4

    c.setFillColor(colors.HexColor("#003366"))
    c.setFont("Helvetica-Bold", 20)
    c.drawString(2*cm, height - 2*cm, "Threat Intelligence Report")

    c.setFont("Helvetica", 12)
    c.setFillColor(colors.black)
    c.drawString(2*cm, height - 3.5*cm, f"IP: {ip}")
    c.drawString(2*cm, height - 4.2*cm, f"Domain: {domain}")
    c.drawString(2*cm, height - 4.9*cm, f"Email: {email}")

    c.drawImage(graph_path, 2*cm, height - 14*cm, width=14*cm, preserveAspectRatio=True)

    c.setFont("Helvetica-Oblique", 10)
    c.setFillColor(colors.gray)
    c.drawString(2*cm, 2*cm, "Generated by Threat Intelligence Dashboard (Secure Edition)")

    c.save()
    return pdf_path
