import os
import pandas as pd
import matplotlib
matplotlib.use("Agg")  # GUI olmayan ortamlarda hata engeli
import matplotlib.pyplot as plt
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from reportlab.platypus import Table, TableStyle
from reportlab.lib.units import cm

def _save_chart(df: pd.DataFrame, x: str, y: str, title: str, filename: str):
    if df.empty or x not in df.columns or y not in df.columns:
        return None
    os.makedirs("reports", exist_ok=True)
    path = f"reports/{filename}"
    plt.figure(figsize=(5, 2))
    plt.bar(df[x].astype(str), df[y], color="#0077cc")
    plt.title(title, fontsize=9)
    plt.xticks(rotation=45, ha="right", fontsize=7)
    plt.tight_layout()
    plt.savefig(path)
    plt.close()
    return path

def build_pdf(df_ip, df_dom, df_em, output_path="reports/threat_report.pdf"):
    os.makedirs("reports", exist_ok=True)
    c = canvas.Canvas(output_path, pagesize=A4)
    width, height = A4
    y = height - 3 * cm

    c.setFont("Helvetica-Bold", 18)
    c.setFillColor(colors.HexColor("#003366"))
    c.drawString(2 * cm, y, "Threat Intelligence Report")
    c.setFillColor(colors.black)
    c.setFont("Helvetica", 10)
    c.drawString(2 * cm, y - 0.6 * cm, datetime.utcnow().strftime("Generated at %Y-%m-%d %H:%M UTC"))
    y -= 1.5 * cm

    def add_section(title, df, x_col, y_col):
        nonlocal y
        if df is None or df.empty:
            return
        if y < 8 * cm:
            c.showPage(); y = height - 3 * cm
        c.setFont("Helvetica-Bold", 12)
        c.drawString(2 * cm, y, title)
        y -= 0.6 * cm
        chart_path = _save_chart(df, x_col, y_col, title, f"{title}.png")
        if chart_path and os.path.exists(chart_path):
            c.drawImage(chart_path, 2 * cm, y - 4.5 * cm, width=13 * cm, height=4 * cm)
            y -= 5 * cm
        cols = df.columns[:4].tolist()
        data = [cols] + df[cols].head(10).values.tolist()
        table = Table(data, colWidths=[(16 * cm) / len(cols)] * len(cols))
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
        ]))
        w, h = table.wrap(0, 0)
        table.drawOn(c, 2 * cm, y - h)
        y -= h + 0.8 * cm

    add_section("IP Analysis", df_ip, "ip", "abuseScore")
    add_section("Domain Analysis", df_dom, "domain", "malicious")
    add_section("Email Breach Analysis", df_em, "email_masked", "count")

    c.setFont("Helvetica-Oblique", 9)
    c.setFillColor(colors.grey)
    c.drawString(2 * cm, 1.5 * cm, "Generated by Threat Intelligence Dashboard (Secure Edition)")
    c.save()
    return output_path
