from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.platypus import Table, TableStyle
import os
from datetime import datetime

def generate_report(data: dict, output_path="reports/threat_report.pdf"):
    os.makedirs("reports", exist_ok=True)
    c = canvas.Canvas(output_path, pagesize=A4)
    width, height = A4

    # Header
    c.setTitle("Threat Intelligence Report")
    c.setFont("Helvetica-Bold", 20)
    c.drawString(50, height - 50, "🧠 Threat Intelligence Report")

    c.setFont("Helvetica", 12)
    c.drawString(50, height - 80, f"Generated at: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}")
    c.drawString(50, height - 100, "Report type: Combined IP / Domain / Email Intelligence")

    # Table Data
    table_data = [["Field", "Value"]]
    for key, value in data.items():
        table_data.append([key, str(value or "—")])

    table = Table(table_data, colWidths=[150, 350])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ]))

    table.wrapOn(c, width, height)
    table.drawOn(c, 50, height - 250)

    # Footer
    c.setFont("Helvetica-Oblique", 9)
    c.setFillColor(colors.grey)
    c.drawString(50, 40, "Confidential Report – Generated by Threat Intelligence Dashboard")

    c.save()
    return output_path
